# Generated by Django 2.1.4 on 2019-03-04 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments_cus', '0003_auto_20190304_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comments_cus.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
