# Generated by Django 2.1.4 on 2019-02-12 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_num_count', '0002_auto_20190212_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnumagg',
            name='read_date',
            field=models.DateField(default=datetime.date(2019, 2, 12)),
        ),
    ]
