# Generated by Django 2.1.4 on 2019-02-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_num_count', '0006_auto_20190217_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnumdetail',
            name='read_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
