# Generated by Django 2.1.4 on 2019-03-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20190212_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='on_deleted',
            new_name='is_deleted',
        ),
    ]
